# Generated by Django 3.1.12 on 2024-12-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20241211_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
