# Generated by Django 5.0.7 on 2024-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("price", models.IntegerField()),
                ("desc", models.TextField(blank=True, null=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Meat", "Meat"),
                            ("Vegetable", "Vegetable"),
                            ("Dessert", "Dessert"),
                            ("Beverage", "Beverage"),
                        ],
                        default="Meat",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
