# Generated by Django 3.1.12 on 2024-12-16 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '分类表',
                'db_table': 'category',
            },
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': '菜品表'},
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='cuisine',
            table='cuisine',
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.category'),
        ),
    ]
