# Generated by Django 3.1.12 on 2024-12-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_auto_20241211_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': '菜品表'},
        ),
        migrations.AlterModelTable(
            name='cuisine',
            table='cuisine',
        ),
    ]
