# Generated by Django 5.1.4 on 2024-12-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_auto_20241216_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
