# Generated by Django 3.1.12 on 2024-12-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20241211_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单表'},
        ),
        migrations.AlterModelOptions(
            name='ordercuisine',
            options={'verbose_name': '订单菜品关联表'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='ordercuisine',
            table='ordercuisine',
        ),
    ]
